language: java
notifications:
  email:
  - arnab.k@gmail.com
branches:
  only:
  - master
before_install:
- sudo apt-get install gnupg
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in secring.gpg.enc -out local.secring.gpg
  -d
- openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in pubring.gpg.enc -out local.pubring.gpg
  -d
- cp local.secring.gpg ~/.gnupg/secring.gpg
- cp local.pubring.gpg ~/.gnupg/pubring.gpg
script: mvn clean deploy --settings maven_settings.xml
env:
  global:
  - secure: lomIaFDtdJDkiTxTtRnR8CsOKAv579lVLYSdFdDiQ23eqtRuJ2pCzW3ameHhBVK12B/SyyxkkUUzdfDkI/omdGANjfWM6LZVo31ubNTdvxRC9VErf2lU/O7bJ7ePkPiixTjebot+z+EXeBhMSkTvSE33nRCEXlm/lP4Qo3L6gDA=
  - secure: kf7/jq1B9jVfeUXoywKZyBd+CuhixYXE/eUKROpfeAD4hmT6IIN8LjssqkGw7cNnME5HT56Jwrl9x01f6OyJEoQEjgmBQIB23/VJfdnNYW1pO55ntIuRSMgSEUSPNg75Cful5TNJm+Y8CY5QUh86o3A6PmBwZFvsS24kdM5M6JA=
  - secure: gIEWwJosRio7hKfGhLfC2ZU64a+UezMdmbizZ+dt6uayuXWl7Ri6lp9VgAsK9VukCJ11XS61Yx/qocW2tjUZreaSdqpaYaT0Ukky6mK+5FTi/IDpjy2RjILO7MdSoVxo7xCVj214QEYIVOv0z/Nl/KPpidUXMSOxlPd3zRQ+oCQ=
  - secure: kEgXEHH8p06xQw0xhdkLTfmQOaPZ9Y5MkdIrA8R99cTUWOlg07DulH+4db73PyO1hQqvqNEz0zgVad8L1toerx4RPUSpb3OoKW+/qTA2AWk3+jqj5wYHLHWyp00FmS4GzL1HkyHbJTH8cG94kuT/lwyXIB/1zZ6jKfCfWPh8z6I=
